name: curate-news-feed

services:
  postgres:
    image: postgres
    container_name: curate-news-feed-postgres
    environment:
      POSTGRES_DB: curate-news-feed
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - curate-news-feed_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  curate-news-feed_postgres_data: